eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://192.168.0.109:8761/eureka/

logging:
  level:
    org.springframework.security: INFO
            
                  
