spring:
  application:
    name: monitoring  

management:
    security:
        enabled: false
info:
  app:
    name: Monitoring  Application
    description: ${info.app.name} is Running on ${server.port} port
