spring:
  application:
    name: product
  datasource.url: jdbc:h2:~/product-service;AUTO_SERVER=TRUE
  jpa.hibernate.ddl-auto: update
  jpa.properties.hibernate.show_sql: true

security:
  oauth2:
    client:
      clientId: product
      clientSecret: password
      accessTokenUri: http://localhost:8090/uaa/oauth/token
      grant-type: client_credentials
      scope: server

management:
    security:
        enabled: false
info:
  app:
    name: Product Spring Boot Application
    description: ${info.app.name} is Running on ${server.port} port

eureka.client.healthcheck.enabled: true
