spring:
  application:
    name: product
  datasource.url: jdbc:h2:~/product-service;AUTO_SERVER=TRUE
  jpa.hibernate.ddl-auto: update
  jpa.properties.hibernate.show_sql: true

management:
    security:
        enabled: false
info:
  app:
    name: Product Application
    description: ${info.app.name} is Running on ${server.port} port

hystrix.command.default.circuitBreaker.requestVolumeThreshold: 5

