spring:
  application:
    name: rest-api
  

management:
    security:
        enabled: false
info:
  app:
    name: Spring Boot RESTAPI Application
    description: REST-API Management End Point
      
