spring:
  application:
    name: rest-api
management:
    security:
        enabled: false
info:
  app:
    name: Spring Boot REST-API Application Project
    description: REST-API  End Point Management
