spring:
  application:
    name: zipkin-server 

management:
    security:
        enabled: false

info:
  app:
    name: Zipkin-Server Application
    description: ${info.app.name} is Running on ${server.port} port
      
